version: '3.8'

networks:
  dev:
    driver: bridge


services:
  groomer-doggy-style:
    depends_on:
      app_db:
        condition: service_healthy
    container_name: groomerdoggystyle-web-api
    ports:
      - "8088:80"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__GroomerDoggyStyle=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=GroomerDoggyStyleDb; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDbDriver
    ports:
        - "5433:5432"
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dev

